export const SEED_PROPERTIES = [
  {
    id: 'sitio-iluminado',
    name: 'Sítio Iluminado',
    location: '📍 Biritiba Mirim / Mogi das Cruzes, SP — 1h de SP',
    type: 'festa',
    badge: '🌟 Destaque',
    price: 'R$699',
    price_unit: '/diária + taxa limpeza',
    guests: 'até 22 pessoas',
    features: [
      '🛏️ 4 quartos',
      '🏊 Piscina c/ hidromassagem',
      '🍕 Churrasqueira + forno de pizza',
      '🎱 Salão de festas e jogos',
      '⚽ Campo de futebol',
      '🏐 Quadra de vôlei',
      '💒 Capela',
      '🌳 Área verde com bambuzal',
      '📶 Wi-Fi',
      '📺 TV a cabo',
      '💧 Água filtrada',
    ],
    description:
      'Sítio espaçoso a 1h de São Paulo. Ideal para festas, retiros e temporadas em família. Piscina com hidromassagem, churrasqueira, forno de pizza, salão de jogos, campo de futebol, quadra de vôlei, capela e muita área verde.',
    images: [
      '/fotos/sitio-externo.jpg',
      '/fotos/piscina-principal.jpg',
      '/fotos/piscina-hidromassagem.jpg',
      '/fotos/piscina-cascata.jpg',
      '/fotos/churrasqueira-forno-pizza.jpg',
      '/fotos/salao-festas.jpg',
      '/fotos/campo-futebol.jpg',
      '/fotos/quadra-volei.jpg',
      '/fotos/capela.jpg',
      '/fotos/sala-madeira.jpg',
      '/fotos/quarto-2.jpg',
      '/fotos/quarto-3.jpg',
      '/fotos/quarto-4.jpg',
      '/fotos/vista-piscina.jpg',
    ],
    sort_order: 0,
    active: true,
  },
  {
    id: 'chacara-mairipoa',
    name: 'Chácara Mairiporã',
    location: '📍 Mairiporã, SP',
    type: 'festa',
    badge: '🎉 Eventos',
    price: 'A consultar',
    price_unit: '',
    guests: 'até 30 pessoas',
    features: [
      '🛏️ 3 quartos',
      '🏊 Piscina',
      '🥩 Churrasqueira',
      '🌳 Área verde',
      '👥 até 30 pessoas',
    ],
    description:
      'Chácara em Mairiporã, ótima para eventos, festas e reuniões de família. Ampla área verde, piscina e churrasqueira.',
    images: [
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80',
      'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&q=80',
    ],
    sort_order: 1,
    active: true,
  },
  {
    id: 'chacara-sao-roque',
    name: 'Chácara São Roque',
    location: '📍 São Roque, SP',
    type: 'temporada',
    badge: '🏖️ Temporada',
    price: 'A consultar',
    price_unit: '',
    guests: 'até 15 pessoas',
    features: [
      '🛏️ 3 quartos',
      '🏊 Piscina',
      '🥩 Churrasqueira',
      '🌿 Área verde',
    ],
    description:
      'Espaço tranquilo em São Roque para férias e temporadas em família. Piscina, churrasqueira e muito verde.',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80',
    ],
    sort_order: 2,
    active: true,
  },
  {
    id: 'chacara-atibaia',
    name: 'Chácara Atibaia',
    location: '📍 Atibaia, SP',
    type: 'temporada',
    badge: '🌿 Natureza',
    price: 'A consultar',
    price_unit: '',
    guests: 'até 20 pessoas',
    features: [
      '🛏️ 4 quartos',
      '🏊 Piscina',
      '🥩 Churrasqueira',
      '⛰️ Contato com a natureza',
    ],
    description:
      'Atibaia é famosa pelo clima ameno. Esta chácara é perfeita para descanso, com piscina e natureza exuberante.',
    images: [
      'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=800&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    ],
    sort_order: 3,
    active: true,
  },
  {
    id: 'chacara-mogi',
    name: 'Chácara Mogi das Cruzes',
    location: '📍 Mogi das Cruzes, SP',
    type: 'festa',
    badge: '🎊 Festas',
    price: 'A consultar',
    price_unit: '',
    guests: 'até 25 pessoas',
    features: [
      '🛏️ 3 quartos',
      '🏊 Piscina',
      '🎉 Salão de festas',
      '🥩 Churrasqueira',
    ],
    description:
      'Ideal para festas e comemorações. Salão coberto, piscina e churrasqueira a poucos km do centro de Mogi.',
    images: [
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    sort_order: 4,
    active: true,
  },
  {
    id: 'sitio-mogi-2',
    name: 'Sítio Mogi das Cruzes 2',
    location: '📍 Mogi das Cruzes, SP',
    type: 'temporada',
    badge: '🌳 Sítio',
    price: 'A consultar',
    price_unit: '',
    guests: 'até 18 pessoas',
    features: [
      '🛏️ 3 quartos',
      '🌊 Rio ou lago',
      '🥩 Churrasqueira',
      '🌳 Área rural',
    ],
    description:
      'Sítio rural tranquilo em Mogi das Cruzes. Ótimo para quem busca paz e contato com a natureza.',
    images: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
    ],
    sort_order: 5,
    active: true,
  },
  {
    id: 'terreno-venda',
    name: 'Terreno à Venda — SP',
    location: '📍 Grande São Paulo, SP',
    type: 'venda',
    badge: '🏷️ Venda',
    price: 'A consultar',
    price_unit: '',
    guests: '—',
    features: [
      '📐 Área a definir',
      '🌳 Área verde',
      '🚗 Acesso asfaltado',
      '📋 Documentação ok',
    ],
    description:
      'Terreno com ótima localização na Grande São Paulo. Documentação em ordem. Entre em contato para mais detalhes.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    ],
    sort_order: 6,
    active: true,
  },
  {
    id: 'apart-olinda',
    name: 'Apartamento Olinda',
    location: '📍 Olinda, PE',
    type: 'temporada',
    badge: '🌊 Praia',
    price: 'A consultar',
    price_unit: '',
    guests: 'até 6 pessoas',
    features: [
      '🛏️ 2 quartos',
      '🏖️ Próximo à praia',
      '📶 Wi-Fi',
      '🏛️ Centro histórico',
    ],
    description:
      'Apartamento confortável em Olinda, Patrimônio Mundial da UNESCO. Perto das praias e do centro histórico de Recife.',
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80',
    ],
    sort_order: 7,
    active: true,
  },
  {
    id: 'imovel-9',
    name: 'Novo Imóvel (Em breve)',
    location: '📍 Em cadastro',
    type: 'temporada',
    badge: '🆕 Novo',
    price: 'Em breve',
    price_unit: '',
    guests: '—',
    features: ['📋 Informações em breve'],
    description:
      'Novo imóvel sendo adicionado ao portfólio. Entre em contato pelo WhatsApp para mais informações.',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    sort_order: 8,
    active: true,
  },
];
